```{r libraries}
# load packages necessary for analysis
library(tidyverse)
library(sf)
library(rgrass7)
library(wesanderson)
library(RSAGA)

theme_set(theme_bw())
standPalette <- c(
	wes_palette("Moonrise3")[1:5],
	wes_palette("Cavalcanti1")[4]
)
```

```{r trees}
# read tree observation data
rawTrees <- read.csv("/opt/doug-fir-productivity/data/trees.csv")

trees <- rawTrees %>%
	mutate(
		plot_id = paste(stand, plot, sep = "-"),
		stand = as.factor(as.character(stand))
	) %>%
	mutate(
		rad.incPred = predict(
			lm(rad.inc ~ dbh.2014, data = .),
			newdata = .
		),
		rad.inc = case_when(
			!is.na(rad.inc) ~ rad.inc,
			is.na(rad.inc) ~ rad.incPred
		)
	) %>%
	mutate(dbh.2009 = dbh.2014 - 2 * rad.inc / 10)

ggplot(data = trees, aes(x = dbh.2014, y = rad.inc, color = stand)) +
	geom_point() +
	scale_color_manual(values = standPalette)

```

```{r increment}
plotSum <- trees %>%
	select(stand, plot_id, species, exp, dbh.2014, dbh.2009) %>%
	gather(year, dbh, contains("dbh")) %>%
	mutate(year = gsub("dbh.", "", year)) %>%
	group_by(stand, plot_id, year) %>%
	summarize(
		tph = sum(exp),
		baph = sum(exp * 0.000078539 * dbh^2)
	) %>%
	mutate(
		qmd = sqrt(baph / tph / 0.000078539),
		sdi = tph * (qmd / 25)^1.605
	)

plotsInc <- plotSum %>%
	gather(attr, value, one_of("tph", "baph", "qmd", "sdi")) %>%
	mutate(attrYear = paste(attr, year, sep = "_")) %>%
	select(stand, plot_id, attrYear, value) %>%
	spread(attrYear, value) %>%
	mutate(
		baInc = baph_2014 - baph_2009,
		baPai = (baph_2014 - baph_2009) / (2014 - 2009),
		baPri = 100 * log(baph_2014 / baph_2009) / (2014 - 2009)
	) %>%
	ungroup() %>%
	mutate(
		baIncSmooth = predict(loess(baInc ~ baph_2009, data = .),
		baIncDetrend = baInc / baIncSmooth)
	)

ggplot(data = plotSum, aes(x = qmd, fill = stand)) +
 	geom_histogram() +
	scale_fill_manual(values = standPalette) +
	facet_wrap(~year) +
	theme_bw()+
	theme(legend.direction = "horizontal", legend.position = "bottom")
```

```{r plotLocs}
# read texture key file that provides mineral soil compositions for each texture classification
soilFile <- "/opt/doug-fir-productivity/data/texturekey_rawls1998.csv"
texture <-  read.csv(soilFile) %>%
	select(-X)

# read plot locations
plotFile <- "/opt/doug-fir-productivity/data/plots.csv"
plots <- read.csv(plotFile) %>%
	left_join(texture, by = "texture") %>%
	mutate(stand = as.factor(as.character(stand)))

plotLocs <- st_as_sf(plots, coords = c("x", "y"), crs = 26910)

```

```{r rasters}
demFile <- "/opt/doug-fir-productivity/data/rasters/dem.tif"
dem <- raster::raster(demFile)

# GRASS #
initGRASS(
  gisBase = "/usr/lib/grass74/",
	home = tempdir(),
	mapset = "PERMANENT",
  override = T
)
      
execGRASS("g.proj", flags = "c", epsg = 26910)

## initialize new mapset inheriting projection info
execGRASS("g.mapset", flags = "c", mapset = "df")

# import raster to GRASS
execGRASS(
	"r.in.gdal",
	parameters = list(input = demFile, output = "dem"),
	flags = c("overwrite")
)

execGRASS("g.region", parameters = list(raster = "dem"))

execGRASS(
	"r.slope.aspect",
	parameters = list(
		elevation = "dem",
		slope = "slope",
		aspect = "aspect",
		format = "percent",
		pcurvature = "pcurvature",
		tcurvature = "tcurvature"
	),
	flags = c("overwrite")
)

execGRASS(
	"r.topidx",
	parameters = list(input = "dem", output = "topidx"),
	flags = c("overwrite")
)

execGRASS(
	"r.mapcalc",
	expression = "stage1 = slope * cos(aspect)",
	flags = c("overwrite")
)

execGRASS(
	"r.mapcalc",
	expression="stage2 = slope * sin(aspect)",
	flags = c("overwrite")
)

topidxFile <- "/opt/doug-fir-productivity/data/rasters/topidx.tif"
slopeFile <- "/opt/doug-fir-productivity/data/rasters/slope.tif"
aspectFile <- "/opt/doug-fir-productivity/data/rasters/aspect.tif"
pcurvatureFile <- "/opt/doug-fir-productivity/data/rasters/pcurvature.tif"
tcurvatureFile <- "/opt/doug-fir-productivity/data/rasters/tcurvature.tif"
stage1File <- "/opt/doug-fir-productivity/data/rasters/stage1.tif"
stage2File <- "/opt/doug-fir-productivity/data/rasters/stage2.tif"

execGRASS(
	"r.out.gdal",
	parameters = list(input = "slope", output = slopeFile)
)
execGRASS(
	"r.out.gdal",
	parameters = list(input = "aspect", output = aspectFile)
)
execGRASS(
	"r.out.gdal",
	parameters = list(input = "pcurvature", output = pcurvatureFile)
)
execGRASS(
	"r.out.gdal",
	parameters = list(input = "tcurvature", output = tcurvatureFile)
)
execGRASS(
	"r.out.gdal",
	parameters = list(input = "stage1", output = stage1File)
)
execGRASS(
	"r.out.gdal",
	parameters = list(input = "stage2", output = stage2File)
)

# perform terrain analysis using SAGA
sagaenv = rsaga.env() # locate SAGA_cmd.exe, allows SAGA modules to be called by R

demSaga = rsaga.import.gdal(
	in.grid = demFile, # imports DEM for use by SAGA
	env=sagaenv
)

# parameters: absolute catchment area, local slope
rsaga.wetness.index(
	in.dem = "/opt/doug-fir-productivity/data/rasters/dem.sgrd",
	out.wetness.index = "/opt/doug-fir-productivity/data/rasters/twi.sgrd",
	area.type = 0,
	slope.type = 0,
	env = sagaenv
)

# calculates topographic position index (TPI)
rsaga.get.modules()

rsaga.geoprocessor(
	lib = "ta_morphometry",
	module = 18,
	param = list(
		DEM = "/opt/doug-fir-productivity/data/rasters/dem.sgrd",
		TPI = "/opt/doug-fir-productivity/data/rasters/tpi300r.sgrd",
		STANDARD = TRUE,
		RADIUS_MIN = 0,
		RADIUS_MAX = 300,
		DW_WEIGHTING = 0,
		DW_IDW_POWER = 1,
		DW_IDW_OFFSET = TRUE,
		DW_BANDWIDTH = 75
	),
	invisible = FALSE,
	display.command = TRUE,
	env = sagaenv
)

rsaga.geoprocessor(
	lib = "ta_morphometry",
	module = 19, # TPI based landform classification
	param = list(
		DEM = "/opt/doug-fir-productivity/data/rasters/dem100.sgrd",
		LANDFORMS="/opt/doug-fir-productivity/data/rasters/landform.sgrd",
		RADIUS_A_MIN = 0,
		RADIUS_A_MAX = 300,
		RADIUS_B_MIN = 300,
		RADIUS_B_MAX = 1500,
		DW_WEIGHTING = 0,
		DW_IDW_POWER = 1,
		DW_IDW_OFFSET = TRUE,
		DW_BANDWIDTH = 75
	),
	invisible = FALSE,
	display.command = TRUE,
	env = sagaenv
)


topidx <- raster::raster(topidxFile)
slope <- raster::raster(slopeFile)
aspect <- raster::raster(aspectFile)
tcurvature <- raster::raster(tcurvatureFile)
pcurvature <- raster::raster(pcurvatureFile)
stage1 <- raster::raster(stage1File)
stage2 <- raster::raster(stage2File)

plotTopo <- plotLocs %>%
	mutate(
		topidx = raster::extract(
			x = topidx,
			y = as(., "Spatial"),
			buffer = radius,
			fun = mean
		),
		slope = raster::extract(
			x = slope,
 			y = as(., "Spatial"),
			buffer = radius,
			fun = mean
		),
		aspect = raster::extract(
			x = aspect,
			y = as(., "Spatial"),
			buffer = radius,
			fun = median
		),
		stage1 = raster::extract(
			x = stage1,
			y = as(., "Spatial"),
			buffer = radius,
			fun = mean
		),
		stage2 = raster::extract(
			x = stage2,
			y = as(., "Spatial"),
			buffer = radius,
			fun = mean
		),
		elev = raster::extract(
			x = dem,
			y = as(., "Spatial"),
			buffer = radius,
			fun = mean
		)
	)

```

```{r canopyHeight}
canHt2009File <- "../doug-fir-productivity/data/rasters/canht2009.tif"
canHt2012File <- "../doug-fir-productivity/data/rasters/canht2012.tif"
canHt2015File <- "../doug-fir-productivity/data/rasters/canht2015.tif"

canHt2009 <- raster::raster(canHt2009File)
canHt2012 <- raster::raster(canHt2012File)
canHt2015 <- raster::raster(canHt2015File)

ht_q95 <- function(x) {
	quantile(x, probs = 0.95,
					 na.rm = TRUE)
}

compute_king_si <- function(ht, age) {
	0.3048 * ((2500 / (((age - 7)^2 / ((ht / 0.3048 - 4.5) +
	0.954038 - 0.0558178 * (age - 7) +
	0.000733819 * (age - 7)^2)) / (0.109757 + 0.00792236 * (age - 7) +
	0.000197693 * (age - 7)^2))) + 4.5)
}

estimate_ht_growth <- function(si, age, years) {
  si.ft <- si / 0.3048
  
  a1 <- 2500
  a2 <- -0.954038
  a3 <- 0.0558178
  a4 <- -0.000733819
  a5 <- 0.109757
  a6 <- 0.00792236
  a7 <- 0.000197693
  
  x1 <- a2 + a5 * (a1 / (si.ft - 4.5))
  x2 <- a3 + a6 * (a1 / (si.ft - 4.5))
  x3 <- a4 + a7 * (a1 / (si.ft - 4.5))
  
  h0 <- 4.5 + age^2 / (x1 + x2 * age + x3 * age^2)
  h1 <- 4.5 + (age + years)^2 / (x1 + x2 * (age + years) + x3 * (age + years)^2)
  
  (h1 - h0) * .3048
}

plotCanHt <- plotLocs %>%
	mutate(
		canHt2009 = raster::extract(
			x = canHt2009,
			y = as(., "Spatial"),
			buffer = radius,
			fun = ht_q95
		),
		canHt2012 = raster::extract(
			x = canHt2012,
		  y = as(., "Spatial"),
		  buffer = radius,
		  fun = ht_q95
		),
	  canHt2015 = raster::extract(
			x = canHt2015,
			y = as(., "Spatial"),
			buffer = radius,
			fun = ht_q95
		)
	)

plotSI <- data.frame(plotCanHt)	%>%
	select(plot_id = plot, contains("canHt"), bh.age) %>%
	mutate(
		siK95_2009 = compute_king_si(age = bh.age - 6, ht = canHt2009),
		siK95_2012 = compute_king_si(age = bh.age - 3, ht = canHt2012),
		siK95_2015 = compute_king_si(age = bh.age, ht = canHt2015)
	) %>%
	mutate(
		htIncPred_09_12 = estimate_ht_growth(
			si = siK95_2009, age = bh.age - 6, years = 3
		),
		htIncPred_12_15 = estimate_ht_growth(
			si = siK95_2012, age = bh.age - 3, years = 3
		)
	)

```

```{r}
# add geographic, topographic, and soil attributes to plot summary table
trainingData <- plotsInc %>%
	left_join(plotTopo) %>%
	left_join(plotSI)

```

